### ISSUE TITLE
[Bug] cell cannot bootstrap successfully in the quick-start example.

### ISSUE THREAD

**Issue by lmsreborn** [deepfabric/elasticell#10]
Info in cell1.log:
2018/01/21 13:00:52.522075 [info] pd-client: connect to pd server succ, addr=<127.0.0.1:20801>
2018/01/21 13:00:52.522669 [fatal] bootstrap: get cluster id from pd failure, pd=<[127.0.0.1:20801 127.0.0.1:20802 127.0.0.1:20803]>, errors:rpc error: code = 2 desc = not leader

Cell1 cannot bootstrap successfully, resulting in cell2 and cell3 cannot elect a leader. This situation happens occasionally.

**Comment by zhangxu19830126** [comment]
This problem is not reproduced on my computer. Can you upload the pd log?
