### ISSUE TITLE
可否讲一下elasticell和pika以及ssdb的优缺点？

### ISSUE THREAD

**Issue by imneov** [deepfabric/elasticell#13]

**Comment by zhangxu19830126** [comment]
1. Elasticell是多副本的，使用Raft作为一致性协议。

**Comment by yingfeng** [comment]
ssdb没有分片，相当于单机存储，尽管有主从复制，但不存在强一致
pika有分片机制，是分布式存储，但没有强一致，也不支持auto-rebalance

**Comment by imneov** [comment]
谢谢两位解答，请问有Elasticell的性能测试数据么？

**Comment by zhangxu19830126** [comment]
这里给出一个大概的数据：
测试环境，3台物理机，千兆网络，sata盘，64核，128G内存。
