### ISSUE TITLE
近期也在参考multi-raft实现，想了解下elasticell的现状及相关问题

### ISSUE THREAD

**Issue by dcosmos** [deepfabric/elasticell#17]
Hi，目前我们也在参考multi-raft相关的实现，感觉elasticell这个项目很有参考意义，就是有以下几个问题想了解下：
（1）elasticell现在是否有用到过生产环境？
（2）近期维护也变的很少了，是有什么原因？项目已经稳定了还是没有时间更新了。
（3）有没有什么已知的性能瓶颈或者是坑？

**Comment by zhangxu19830126** [comment]
1. 还没有在生产使用，目前我们内部在小规模使用，还算稳定，没有发现什么问题。

**Comment by dcosmos** [comment]
好的，多谢大佬！
